name: Daily Leaderboard Update and Visualization

on:
  schedule:
    - cron: '0 4 * * *' # Runs every day at 04:00 UTC
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessary to commit changes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your preferred version

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install necessary libraries for both scripts
          pip install pandas numpy plotly requests

      - name: Fetch and Save Daily Snapshot
        run: python fetch_daily_snapshot.py # Run the fetch script first

      - name: Generate Visualization from All Snapshots
        run: python generate_visualization.py # Run the visualization script next

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update: Leaderboard snapshot and index.html"
          # Commit the newly created snapshot in data/ and the updated index.html
          # Committing the whole 'data/' directory is simplest here.
          file_pattern: "index.html data/"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
          # Optional: Add skip_dirty_check: true if needed, but usually not required
          # Optional: Add skip_fetch: true if you are sure no other changes happened
